pal_swap_init_system(shd_pal_swapper)
enum states 
{
    normal,
    titlescreen,
    slap,
    charge,
    climbwall,
    knightpepslopes,
    portal,
    handstandjump,
    gottreasure,
    knightpep,
    knightpepattack,
    bombpep,
    grabbing,
    shotgunjump,
    stunned,
    facestomp,
    timesup,
    machroll,
    pistol,
    shotgun,
    superslam,
    slam,
    grind,
    grab,
    punch,
    backkick,
    uppunch,
    shoulder,
    backbreaker,
    bossdefeat,
    bossintro,
    current,
    idle,
    turn,
    walk,
    land,
    hit,
    stun,
    grabbed,
    gameover,
    freefallprep,
    runonball,
    boulder,
    keyget,
    tackle,
    slipnslide,
    ladder,
    jump,
    victory,
    comingoutdoor,
    Sjump,
    Sjumpprep,
	Sjumpland,
    crouch,
	machfreefall,
    crouchjump,
    crouchslide,
    mach1,
    mach2,
    mach3,
	mach4, // this isnt a real state but it will send the player into mach4 if called (thanks to mach4mode variable!)
    machslide,
    bump,
    hurt,
    freefall,
    freefallland,
    hang,
    door,
	Throw, // EPIC shoutout to dist for suggesting how to make gm not shit itself compiling this enum
	
}
room = golf_room1;
obj_player.facehurt = 0
obj_player.targetDoor = "A"
obj_player.targetRoom = golf_room1;